/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TestData = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'questions' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CommunityActivity = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Opt(IDL.Text),
  'content' : IDL.Text,
  'createdAt' : Time,
});
export const NoticeboardPost = IDL.Record({
  'author' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'leisureCentreArea' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'contactPreferences' : IDL.Text,
});
export const Appointment = IDL.Record({
  'patient' : IDL.Principal,
  'isConsultant' : IDL.Bool,
  'time' : Time,
  'staff' : IDL.Principal,
  'location' : IDL.Text,
});
export const Assessment = IDL.Record({
  'hadScore' : IDL.Int,
  'patient' : IDL.Principal,
  'copmScore' : IDL.Int,
  'assessmentDate' : Time,
  'shuttleWalkScore' : IDL.Int,
  'videoRecord' : IDL.Opt(ExternalBlob),
  'vitalObservations' : IDL.Text,
  'meamsScore' : IDL.Int,
});
export const Patient = IDL.Record({
  'conditionSummary' : IDL.Text,
  'goals' : IDL.Text,
  'profile' : UserProfile,
  'isDischarged' : IDL.Bool,
});
export const ProgrammePlan = IDL.Record({
  'patient' : IDL.Principal,
  'completionStatus' : IDL.Bool,
  'frequency' : IDL.Text,
  'interventions' : IDL.Vec(IDL.Text),
});
export const Affirmation = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'author' : IDL.Opt(IDL.Text),
});
export const TestProgress = IDL.Record({
  'answers' : IDL.Vec(IDL.Text),
  'completed' : IDL.Bool,
  'testId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAffirmation' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addAssessment' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        Time,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'addCommunityActivity' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addNoticeboardPost' : IDL.Func([IDL.Text], [], []),
  'addTest' : IDL.Func([TestData], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Text, Time, IDL.Bool],
      [],
      [],
    ),
  'completeTest' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'createJournalEntry' : IDL.Func([IDL.Opt(IDL.Text), IDL.Text], [IDL.Nat], []),
  'createProgrammePlan' : IDL.Func(
      [IDL.Principal, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
  'dischargePatient' : IDL.Func([IDL.Principal], [], []),
  'getAllCommunityActivities' : IDL.Func(
      [],
      [IDL.Vec(CommunityActivity)],
      ['query'],
    ),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getAllNoticeboardPosts' : IDL.Func(
      [],
      [IDL.Vec(NoticeboardPost)],
      ['query'],
    ),
  'getAllTests' : IDL.Func([], [IDL.Vec(TestData)], ['query']),
  'getAllUsersSortedByName' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAppointmentsForPatient' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAssessmentsForPatient' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Assessment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJournalEntry' : IDL.Func([IDL.Nat], [IDL.Opt(JournalEntry)], ['query']),
  'getPatient' : IDL.Func([IDL.Principal], [IDL.Opt(Patient)], ['query']),
  'getProgrammePlansForPatient' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ProgrammePlan)],
      ['query'],
    ),
  'getRandomAffirmation' : IDL.Func([], [IDL.Opt(Affirmation)], ['query']),
  'getUserGrowthSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'streak' : IDL.Nat,
          'completedTests' : IDL.Nat,
          'journalCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTestProgress' : IDL.Func([], [IDL.Vec(TestProgress)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'onboardPatient' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startTest' : IDL.Func([IDL.Text], [], []),
  'updateProgrammePlanStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TestData = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'questions' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CommunityActivity = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Opt(IDL.Text),
    'content' : IDL.Text,
    'createdAt' : Time,
  });
  const NoticeboardPost = IDL.Record({
    'author' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'leisureCentreArea' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'contactPreferences' : IDL.Text,
  });
  const Appointment = IDL.Record({
    'patient' : IDL.Principal,
    'isConsultant' : IDL.Bool,
    'time' : Time,
    'staff' : IDL.Principal,
    'location' : IDL.Text,
  });
  const Assessment = IDL.Record({
    'hadScore' : IDL.Int,
    'patient' : IDL.Principal,
    'copmScore' : IDL.Int,
    'assessmentDate' : Time,
    'shuttleWalkScore' : IDL.Int,
    'videoRecord' : IDL.Opt(ExternalBlob),
    'vitalObservations' : IDL.Text,
    'meamsScore' : IDL.Int,
  });
  const Patient = IDL.Record({
    'conditionSummary' : IDL.Text,
    'goals' : IDL.Text,
    'profile' : UserProfile,
    'isDischarged' : IDL.Bool,
  });
  const ProgrammePlan = IDL.Record({
    'patient' : IDL.Principal,
    'completionStatus' : IDL.Bool,
    'frequency' : IDL.Text,
    'interventions' : IDL.Vec(IDL.Text),
  });
  const Affirmation = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'author' : IDL.Opt(IDL.Text),
  });
  const TestProgress = IDL.Record({
    'answers' : IDL.Vec(IDL.Text),
    'completed' : IDL.Bool,
    'testId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAffirmation' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addAssessment' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          Time,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'addCommunityActivity' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addNoticeboardPost' : IDL.Func([IDL.Text], [], []),
    'addTest' : IDL.Func([TestData], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Text, Time, IDL.Bool],
        [],
        [],
      ),
    'completeTest' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'createJournalEntry' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createProgrammePlan' : IDL.Func(
        [IDL.Principal, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
    'dischargePatient' : IDL.Func([IDL.Principal], [], []),
    'getAllCommunityActivities' : IDL.Func(
        [],
        [IDL.Vec(CommunityActivity)],
        ['query'],
      ),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getAllNoticeboardPosts' : IDL.Func(
        [],
        [IDL.Vec(NoticeboardPost)],
        ['query'],
      ),
    'getAllTests' : IDL.Func([], [IDL.Vec(TestData)], ['query']),
    'getAllUsersSortedByName' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAppointmentsForPatient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAssessmentsForPatient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Assessment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJournalEntry' : IDL.Func([IDL.Nat], [IDL.Opt(JournalEntry)], ['query']),
    'getPatient' : IDL.Func([IDL.Principal], [IDL.Opt(Patient)], ['query']),
    'getProgrammePlansForPatient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ProgrammePlan)],
        ['query'],
      ),
    'getRandomAffirmation' : IDL.Func([], [IDL.Opt(Affirmation)], ['query']),
    'getUserGrowthSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'streak' : IDL.Nat,
            'completedTests' : IDL.Nat,
            'journalCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTestProgress' : IDL.Func([], [IDL.Vec(TestProgress)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'onboardPatient' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startTest' : IDL.Func([IDL.Text], [], []),
    'updateProgrammePlanStatus' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };