/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Affirmation {
  'id' : bigint,
  'text' : string,
  'author' : [] | [string],
}
export interface Appointment {
  'patient' : Principal,
  'isConsultant' : boolean,
  'time' : Time,
  'staff' : Principal,
  'location' : string,
}
export interface Assessment {
  'hadScore' : bigint,
  'patient' : Principal,
  'copmScore' : bigint,
  'assessmentDate' : Time,
  'shuttleWalkScore' : bigint,
  'videoRecord' : [] | [ExternalBlob],
  'vitalObservations' : string,
  'meamsScore' : bigint,
}
export interface CommunityActivity {
  'name' : string,
  'description' : string,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface JournalEntry {
  'id' : bigint,
  'title' : [] | [string],
  'content' : string,
  'createdAt' : Time,
}
export interface NoticeboardPost {
  'author' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface Patient {
  'conditionSummary' : string,
  'goals' : string,
  'profile' : UserProfile,
  'isDischarged' : boolean,
}
export interface ProgrammePlan {
  'patient' : Principal,
  'completionStatus' : boolean,
  'frequency' : string,
  'interventions' : Array<string>,
}
export interface TestData {
  'id' : string,
  'name' : string,
  'description' : string,
  'questions' : Array<string>,
}
export interface TestProgress {
  'answers' : Array<string>,
  'completed' : boolean,
  'testId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'leisureCentreArea' : string,
  'name' : string,
  'role' : UserRole,
  'contactPreferences' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAffirmation' : ActorMethod<[string, [] | [string]], undefined>,
  'addAssessment' : ActorMethod<
    [
      Principal,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      Time,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'addCommunityActivity' : ActorMethod<[string, string, string], undefined>,
  'addNoticeboardPost' : ActorMethod<[string], undefined>,
  'addTest' : ActorMethod<[TestData], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<
    [Principal, Principal, string, Time, boolean],
    undefined
  >,
  'completeTest' : ActorMethod<[string, Array<string>], undefined>,
  'createJournalEntry' : ActorMethod<[[] | [string], string], bigint>,
  'createProgrammePlan' : ActorMethod<
    [Principal, Array<string>, string],
    undefined
  >,
  'deleteJournalEntry' : ActorMethod<[bigint], undefined>,
  'dischargePatient' : ActorMethod<[Principal], undefined>,
  'getAllCommunityActivities' : ActorMethod<[], Array<CommunityActivity>>,
  'getAllJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getAllNoticeboardPosts' : ActorMethod<[], Array<NoticeboardPost>>,
  'getAllTests' : ActorMethod<[], Array<TestData>>,
  'getAllUsersSortedByName' : ActorMethod<[], Array<UserProfile>>,
  'getAppointmentsForPatient' : ActorMethod<[Principal], Array<Appointment>>,
  'getAssessmentsForPatient' : ActorMethod<[Principal], Array<Assessment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJournalEntry' : ActorMethod<[bigint], [] | [JournalEntry]>,
  'getPatient' : ActorMethod<[Principal], [] | [Patient]>,
  'getProgrammePlansForPatient' : ActorMethod<
    [Principal],
    Array<ProgrammePlan>
  >,
  'getRandomAffirmation' : ActorMethod<[], [] | [Affirmation]>,
  'getUserGrowthSummary' : ActorMethod<
    [],
    { 'streak' : bigint, 'completedTests' : bigint, 'journalCount' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTestProgress' : ActorMethod<[], Array<TestProgress>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'onboardPatient' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startTest' : ActorMethod<[string], undefined>,
  'updateProgrammePlanStatus' : ActorMethod<[Principal, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];